### ISSUE TITLE
Check for missing abbreviation markup

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#10]
There are a couple of instances of `M.P.` for example that don’t have wrapping abbr elements (in that case with `class="initialism"`). Can you read through https://standardebooks.org/manual/1.0.0/8-typography#8.10 and then check the text for other abbreviations? A quick search turned up D.C., M.P., and N.B., and I guess there might be more.

**Comment by atwood97** [comment]
Done.
