### ISSUE TITLE
Bridgehead semantics

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#11]
Bridgeheads and their associated title should be wrapped in a header element. Have a read of https://standardebooks.org/manual/1.0.0/7-high-level-structural-patterns#7.2.7.

As for their use lower down in the chapters (e.g. https://github.com/atwood97/agatha-christie_the-man-in-the-brown-suit/blob/550ee2aa321ba0be16d1b3b932dff08b68d785d0/src/epub/text/chapter-17.xhtml#L47) I’m not sure we’ve got an entirely suitable markup pattern. @acabal, do you have an opinion?

**Comment by acabal** [comment]
Bridgheads only belong in headers by definition. What does this line look like in print?

**Comment by atwood97** [comment]
Where appropriate, I've changed <p epub:type="bridgehead"> lines to a plain <p> wrapped in a <header> tag.
