### ISSUE TITLE
<abbr class="time eoc"> not at the end of a clause

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#12]
There are quite a few examples of `<abbr class="time eoc">` where the abbreviation isn‘t at the end of a clause (`eoc`). Can you remove the `eoc` class in places where the abbreviation doesn’t finish the sentence?

**Comment by atwood97** [comment]
These have been corrected. I rolled back the large commit that covered too many varied things, and in redoing my edits and other changes (one commit at a time) I avoided the mistake that put in the inappropriate "time eoc" classes.
