### ISSUE TITLE
Clue image updates

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#14]
A few things to do with `clue.jpg`:

- First up, the jpg should be traced to be an SVG. This can be done with Inkscape, and then the SVG can be processed with (for example) SVGOMG https://jakearchibald.github.io/svgomg/ to strip out as much unnecessary code as possible. People will be happy to help with this on the mailing list.
- Once that’s done, review the documentation at https://standardebooks.org/manual/1.0.0/7-high-level-structural-patterns#7.8. The image should have `epub:type="z3998:illustration se:image.color-depth.black-on-transparent"`, and should be wrapped with a `<figure>` element.
- The figure will require more CSS: https://standardebooks.org/manual/1.0.0/7-high-level-structural-patterns#7.8.4
- Finally, an LoI page will need to be added (https://standardebooks.org/manual/1.0.0/7-high-level-structural-patterns#7.9), and the spine, manifest and ToC regenerated.

Ask if you need help with any of these steps.

**Comment by robinwhittleton** [comment]
Oh, and of course once that’s done, the `#cursiveclue` rule in the CSS can be removed.

**Comment by atwood97** [comment]
All done.
