### ISSUE TITLE
Missing CSS

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#15]
You have a dedication page, so you need to include the dedication CSS in your local CSS: https://standardebooks.org/manual/1.0.0/7-high-level-structural-patterns#7.3.

Same for bridgeheads: https://standardebooks.org/manual/1.0.0/7-high-level-structural-patterns#7.2.7.2.

**Comment by atwood97** [comment]
I have added the dedication CSS to the local.css. Will add CSS for bridgeheads after decision about whether "bridgehead" is the correct epub type.

**Comment by atwood97** [comment]
Where necessary, I've change <p> designated as bridgeheads to plain <p> paragraphs wrapped in a <header> tag. And I've added the appropriate bridgehead CSS to local.css.
