### ISSUE TITLE
Hide lint warning for missing full stop in the dedication 

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#23]
If there’s no full stop in the dedication that’s fine, but we need to add an se-lint-ignore.xml file to the root with an explanation as to why we’re ignoring the `t-011` linting error. For an example file see https://github.com/standardebooks/john-milton_paradise-lost/blob/master/se-lint-ignore.xml; you’ll need to ignore `t-011` in `dedication.xhtml`.

**Comment by atwood97** [comment]
Done.
