### ISSUE TITLE
Some changes to the clue.svg image markup

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#24]
1. We need to add epub:type="z3998:illustration se:image.color-depth.black-on-transparent" to the img element.
2. The image should be wrapped in a `<figure>`, not a `<div>`, and appropriate CSS should be added to local.css. See https://standardebooks.org/manual/1.0.0/7-high-level-structural-patterns#7.8.4 for more info.
3. We can assume that Christie drew the clue, so can you add `<meta property="role" refines="#author" scheme="marc:relators">ill</meta>` to the author section of content.opf after the `aut` role.

**Comment by atwood97** [comment]
Done
