### ISSUE TITLE
file-as for artist is missing a name

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#3]
https://github.com/atwood97/agatha-christie_the-man-in-the-brown-suit/blob/550ee2aa321ba0be16d1b3b932dff08b68d785d0/src/epub/content.opf#L67

The artist’s first name is `Georges-Victor`, so the file-as should be `Hugo, Georges-Victor`.

**Comment by atwood97** [comment]
Artist's first name has been corrected.
