### ISSUE TITLE
Missing long description

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#5]
We need a long description in place in the content.opf. This is the text that appears on the SE website below the book tags (for example on https://standardebooks.org/ebooks/agatha-christie/the-secret-adversary starting with “_The Secret Adversary_, Agatha Christie’s second novel…”. This needs to be written by you and will be donated to the public domain. More info at https://standardebooks.org/manual/1.0.0/9-metadata#9.6.2. It’s probably worth reading a few of these for other publications to understand what we’re looking for.

We can also drop the publication note element entirely if there’s nothing special to write up.

**Comment by atwood97** [comment]
Long description has been added.
