### ISSUE TITLE
Add ODPT as transcribers to content.opf

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#6]
We’re crediting them in the colophon, so they should be credited in content.opf too. You can copy the block from another production (for example https://github.com/standardebooks/e-e-smith_triplanetary/blob/3720936621b91e9f041e48752e44f44766362869/src/epub/content.opf#L72-L75).

The existing Anonymous Volunteer `id`/`refines` attributes should be changed to `transcriber-1`, then the new ODPT `id`/`refines` attributes should be `transcriber-2`.

**Comment by atwood97** [comment]
ODPT added as transcriber-2 to content.opf
