### ISSUE TITLE
Couple of dedication fixes

### ISSUE THREAD

**Issue by robinwhittleton** [atwood97/agatha-christie_the-man-in-the-brown-suit#8]
Can you wrap `E. A. B.` with an `<abbr class="name">`, and make sure that there’s a full stop at the end of the last line (i.e. `“Mystery of the Mill House.”</p>`).

**Comment by atwood97** [comment]
I have added the <abbr> tag, but I have not added the full stop at the end of the last line. It is not in the original, and the dedication is not a complete sentence.
